version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=file:./database/app.db
      - JWT_SECRET=your_super_secret_jwt_key_change_this_in_production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      # 可选: 如果你的域名使用了CDN，在这里配置CDN域名
      # - CDN_URL=https://cdn.your-domain.com
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
    restart: unless-stopped
