version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/imgbed?schema=public
      - JWT_SECRET=your_super_secret_jwt_key_change_this_in_production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      # 可选: 如果你的域名使用了CDN，在这里配置CDN域名
      # - CDN_URL=https://cdn.your-domain.com
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=imgbed
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/usr/share/nginx/html/uploads
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
